# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c420c3b0a671886e797d17264e1234a03270280b7bfcbdf0d8494cf80b85232919335b66d6ef3a4ff4622e062a7e230f424db4310c7ac359707bf3aa85e8f4

test:
  secret_key_base: d283d2095ef91b13c4cccfe7f04039450d54512bdf70505bc3d183674451603488d2caebb4d94b7b4544f0e9f72f50cb9f91f445ccf0642a6d987698a786e68b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
